#
# Container for Driver
#
# Expects the following environment variables:
# Crossbar settings:
# CROSSBAR_HOST (default 0.0.0.0)
# CROSSBAR_PORT (default 8080)
# Ser2net (bridge between serial port and TCP for Smoothie)
# SMOOTHIE_HOST (default 0.0.0.0)
# SMOOTHIE_PORT (defaults 3333)
#
FROM common-build

COPY * /home/sandbox-driver/
WORKDIR /home/sandbox-driver
RUN pip3 install autobahn==0.10.3

RUN rm -rf /var/cache/apk/*
ENTRYPOINT ["tar", "-cvz", "/usr/lib/python3.5/site-packages/", "/home/sandbox-driver"]